import "./globals.css";
import { Inter } from "next/font/google";
import { Header, Footer, Tabs } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Classics Wifi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        {/* <Tabs /> */}

        <Footer />
      </body>
    </html>
  );
}
